### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by mertkemal1131** [nftblackmagic/catvton-flux#21]
(flux) C:\Users\USER\Desktop\catvton-flux>python app.py
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\catvton-flux\app.py", line 13, in <module>
    subprocess.run("rm -rf /data-nvme/zerogpu-offload/*", env={}, shell=True)
  File "C:\Users\USER\anaconda3\envs\flux\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\USER\anaconda3\envs\flux\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\USER\anaconda3\envs\flux\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] Parametre hatalı

(flux) C:\Users\USER\Desktop\catvton-flux>python app_lora.py
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\catvton-flux\app_lora.py", line 13, in <module>
    subprocess.run("rm -rf /data-nvme/zerogpu-offload/*", env={}, shell=True)
  File "C:\Users\USER\anaconda3\envs\flux\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\USER\anaconda3\envs\flux\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\USER\anaconda3\envs\flux\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] Parametre hatalı

(flux) C:\Users\USER\Desktop\catvton-flux>python app_n0_lora.py
python: can't open file 'C:\\Users\\USER\\Desktop\\catvton-flux\\app_n0_lora.py': [Errno 2] No such file or directory

(flux) C:\Users\USER\Desktop\catvton-flux>python app_no_lora.py
CUDA installation found at: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6
Loading diffusion model ...
Fetching 3 files: 100%|██████████████████████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 15.84it/s]
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers█| 2/2 [00:00<00:00, 15.97it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:00<00:00, 14.91it/s]
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\catvton-flux\app_no_lora.py", line 49, in <module>
    ).to(device)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 460, in to
    module.to(device, dtype)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\transformers\modeling_utils.py", line 2861, in to
    return super().to(*args, **kwargs)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\torch\nn\modules\module.py", line 1160, in convert
    return t.to(
  File "C:\Users\USER\anaconda3\envs\flux\lib\site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

these are the problems i am facing

**Comment by nftblackmagic** [comment]
It looks like CUDA version issue. Didn't try it in windows env. It's hard to debug without specific env information.

**Comment by mertkemal1131** [comment]
I was sble to get app_no_lora working but getting any results takes more than 3 hours, will be decreased?
